# Generated by Django 4.2.16 on 2024-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_encontrado', models.DateField()),
            ],
        ),
    ]
